### ISSUE TITLE
Mock data 추가

### ISSUE THREAD

**Issue by Jinho1011** [wit-kr/sullog_web#12]
## Mocking data 추가
- msw 사용해볼까요

**Comment by shinwonse** [comment]
어 지금 모킹할만한거 있나요?

**Comment by Jinho1011** [comment]
전통주 데이터 가능할거 같긴 한데

**Comment by shinwonse** [comment]
일단 레이아웃 합치고 생각해보죠 ㄱㄱ

**Comment by Jinho1011** [comment]
http://52.78.33.186:8080/sullog/alchol/getAlchols
서버가 나와서 필요 없어짐
